micronaut:
  application:
    name: productService

grpc:
  server:
    port: 50053

datasources:
  default:
    url: jdbc:postgresql://localhost:5434/productsdatabase
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
