micronaut:
  application:
    name: productService

grpc:
  server:
    port: 50053

datasources:
  default:
    url: jdbc:h2:mem:productDb;MVCC=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
