micronaut:
  application:
    name: shopping-cart

grpc:
  channels:
    customer:
      target: localhost:50052
      plaintext: true
  server:
    port: 50051

rabbitmq:
  username: user
  password: user

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/shoppingdatabase
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

jpa.default.properties.hibernate.hbm2ddl.auto: create